[package]
name = "buncher"
version = "0.2.2"
authors = ["Miguel Rodríguez Pérez <miguel@det.uvigo.gal>"]
edition = "2018"

[dependencies]
structopt = "0.2"
structopt-derive = "0.2"

[dependencies.eee-hyst]
git = "https://github.com/migrax/HystEEE.git"
